### ISSUE TITLE
support glob in --generate-hashes

### ISSUE THREAD

**Issue by graingert** [peterdemin/pip-compile-multi#154]
I always want to generate-hashes in all environments

**Comment by peterdemin** [comment]
Hi Thomas, `--generate-hashes` option is contagious - it spreads to all linked files (both dependents and depended by) because pip doesn't allow to provide hash just to a part of packages. It has to be all or nothing.
So if you have a completely connected graph of requirement files, then mentioning any one of them in this option will make it work for all.
Having that in mind, do you think, that support for glob expressions is still useful?

**Comment by graingert** [comment]
How about just --generate-hashes-all?

**Comment by graingert** [comment]
Because I don't have a connected graph

**Comment by peterdemin** [comment]
I see. `pip-compile-multi` itself has three disconnected graphs:
https://github.com/peterdemin/pip-compile-multi/blob/1833a968eaadd320230a64ef86ab44f8c1e63881/tox.ini#L53
```
pip-compile-multi -n local27 -g local27 -i txt -o hash
pip-compile-multi -n local -n testwin -g local -g testwin -i txt -o hash
```
What's your invocation look like now?
I like `-G, --generate-hashes-all` flag more than globbing. Could open a PR with this feature?

**Comment by graingert** [comment]
generate-hashes-all wfm
