### ISSUE TITLE
Respect constraint files

### ISSUE THREAD

**Issue by jmcarp** [peterdemin/pip-compile-multi#257]
`pip-tools` supports using constraint files as well as requirement files to constraint version resolution: https://github.com/jazzband/pip-tools#workflow-for-layered-requirements. But I don't think `pip-compile-multi` supports constraint files (sorry if I misread). I think it would be useful to respect constraint files in `pip-compile-multi`, and specifically to interpret "-c foo.txt" as equivalent to "-r foo.in". If the feature makes sense, I'd be happy to attempt a pull request.

**Comment by peterdemin** [comment]
`pip-compile-multi` supports constraint files. Take a look at [--autoresolve](https://pip-compile-multi.readthedocs.io/en/latest/features.html#autoresolve-cross-file-conflicts) for example.

**Comment by jmcarp** [comment]
Sorry if I'm misunderstanding, but what I'm asking about is whether `pip-compile-multi` will treat `-c` in a `*.in` file as a dependency. Looking at the code, I don't think it does: https://github.com/peterdemin/pip-compile-multi/blob/319dc896fe828af4169cdf3c0ef1d30733cda589/pipcompilemulti/environment.py#L21. Looking at the workflow in https://github.com/jazzband/pip-tools#workflow-for-layered-requirements, a user might have a `foo.in` file that references `-c bar.txt`, and in that case I would want to compile `bar.in` before `foo.in`. Does that make sense?

**Comment by peterdemin** [comment]
I used it before. Worked as expected.

**Comment by jmcarp** [comment]
It's not doing what I'm expecting--let me know if I'm misunderstanding. I have two files:

```
# requirements.in
requests
```

```
# requirements-dev.in
-c requirements.txt
pytest
```

Running `pip-compile` begins with `Locking requirements/requirements-dev.in to requirements/requirements-dev.txt. References: []`. This isn't what I'm looking for: requirements-dev.in has a constraint on requirements.txt, so we should lock requirements.in first. Unless I'm missing something, this is modeled directly on https://github.com/jazzband/pip-tools#workflow-for-layered-requirements.

**Comment by peterdemin** [comment]
Trying to understand your use case. Do you want to have `requirements-dev.txt` install only dev requirements, without installing packages listed in `requirements.in`? If so, this setup will achieve exactly that. A constraint is not a reference. And both requirements.in and requirements-dev.in will get compiled (probably in a wrong order though).

What I usually see is little different - dev environment would completely include all base environment packages and add more. This relation is described with `-r`, not `-c`.
The reason is that you need all dependencies installed in order to `pytest` to pass.
`-c` is needed when you want to keep some versions in sync, but not install all the packages from the linked file.

Also, if using `-r`, you should point to `.in` file, not `.txt` file. In your example that would be:
```
# requirements-dev.in
-r requirements.in
pytest
```

After compiling, the command `pip install -r requirements-dev.txt` will install both base packages from `requirements.txt` and dev packages from `dev-requirements.txt`.

**Comment by peterdemin** [comment]
Closing for now. I recommend reading https://pip-compile-multi.readthedocs.io/en/latest/why.html to better understand the intended workflow.
@jmcarp let me know if you identify a use case, that isn't supported by pip-compile-multi.

**Comment by jmcarp** [comment]
Thanks. I'm looking at the workflow described in https://github.com/jazzband/pip-tools#workflow-for-layered-requirements. It's pretty simple, so I just wrote a little script to implement it.
