### ISSUE TITLE
pip-compile-verify should verify changes in setup.py or setup.cfg after adding new package

### ISSUE THREAD

**Issue by ofekisr** [peterdemin/pip-compile-multi#273]
As in the title 
pip-compile verify if pip-compile-multi run after changes in "in" files but 
what if my "in" file contains the line:
"-e file:." 

using version 2.4.1

**Comment by peterdemin** [comment]
I don't think tracking changes in `setup.py` is feasible in the general case. Because `setup.py` is executable and it can import other files and read requirements dynamically. So that package requirements may change without any change to `setup.py`.
I would suggest storing all requirements in separate `requirements` files and reading them from `setup.py`. This way all changes to requirements would get detected by `pip-compile-multi verify` and you can have `-e file:.` in `requirements.in` file.
Note of caution though: having `-e file:.` in the requirements file is incompatible with having hashes for packages, which is considered a best security practice.
Closing the issue, as "won't fix" for now.

**Comment by ofekisr** [comment]
assume my package name is "my-package" and setup.py contains some entry_points 
@peterdemin 
In any non-production environment, the package is installed  by pip install -r <**.txt> 
so If I omit "-e file:." from the base.in
How can I ensure the entry_points will be installed too ?

**Comment by peterdemin** [comment]
`-e file:.` is copied to .txt file during compilation, so it's okay to include it. And when included, it'll reinstall entry points each time.
Verify is a separate concern though. I'm not sure I understand the whole situation.

**Comment by ofekisr** [comment]
As a package contributor, I would like to install all requirements via a requirement file.
while developing new contributions, I should use the package entry points. for using those entry points I have to install the package I currently develop into it. I inserted the "-e file:." into the requirements file to ease the process.

but you suggest I omit it if I would like to use hashes for packages

so I'm confused about how can I achieve using of hashes and ensure the package entry_points will be installed too

**Comment by peterdemin** [comment]
What I usually see in big projects is a multi-step installation process. The first, typically, is the blessed version of pip and Cython. Then all the requirements. And the last step is `pip install -e .`.
Hashes are incompatible with development mode installation at the `pip install` level.

**Comment by ofekisr** [comment]
> What I usually see in big projects is a multi-step installation process. The first, typically, is the blessed version of pip and Cython. Then all the requirements. And the last step is `pip install -e .`.
> Hashes are incompatible with development mode installation at the `pip install` level.

Thanks!

Actually, I'm using your tips here and reviewed what you have done in the setup.py file to adapt it so I can use 
pip-compile-multi in better proper way. 
The only thing I didn't understand is why did you use "base.in" instead of "base.txt" as requirement file content in setup.py 
as well as I use the base.txt to install and not base.in
