### ISSUE TITLE
Feature: support `--unsafe-package`

### ISSUE THREAD

**Issue by schmidt-jake** [peterdemin/pip-compile-multi#365]
# Feature Request

Add support for `pip-compile`'s `--unsafe-package` arg to allow users to specify unsafe packages. While `pip-compile-multi` has an `--allow-unsafe` flag, this does not allow specifying custom unsafe packages.

## Example usage

```bash
pip-compile-multi --directory=requirements --allow-unsafe=torch --allow-unsafe=torchvision
```

**Comment by peterdemin** [comment]
Hmm... AFAIK only pip and setuptools are considered unsafe. torch and torchvision are safe packages.
Could you please provide a use case for this feature?

**Comment by schmidt-jake** [comment]
Maybe this is the wrong feature to enact my use case. But my use case is that I have a custom version of torch (precompiled with a particular CUDA version) that I don't want to pin in my lockfile.

**Comment by peterdemin** [comment]
Would compatible releases help for this? https://pip-compile-multi.readthedocs.io/en/latest/features.html#compatible-releases

**Comment by schmidt-jake** [comment]
Ahh, potentially! Maybe I'm just dumb, but after reading the documentation of that feature, an example would really help.

**Comment by schmidt-jake** [comment]
Ah, [this](https://github.com/peterdemin/pip-compile-multi/blob/master/pipcompilemulti/features/compatible.py#L45) docstring was helpful.

**Comment by peterdemin** [comment]
Yeah, I agree. The doc is not detailed enough. Here's how I used this feature with the internal packages. I always wanted to install the latest version. All internal packages were prefixed with the project name.
Here's the outline.
Let's say, `project-a` depends on `project-b`, and we don't want to update lock files on every change. But we also want to do backward-incompatible changes in project-b every once in a while.
We then run `pip-compile-multi -c 'project-*'` and it uses `~=` instead of `==` for `project-b`.
`requirements.txt`:
```
project-b~=0.1.123
```
This means, that pip will install the latest version of `project-b` which satisfies these constraints: `>=0.1.123, <0.2`.
When we need to introduce backward-incompatible changes, or a new transitive dependency for project-b, we would bump major (or minor) version, and handle upgrades in `project-a` manually with relocking to `1.0.x`.

Does it make sense?

**Comment by schmidt-jake** [comment]
Thank you, yes that does make sense. I just tried using it, and unfortunately it didn't work for me. Here's why:

The pre-installed package I don't want to clobber is pinned as `torch==1.13.0a0+340c412`. All of the following will clobber it:
- `pip install "torch~=1.13"`
- `pip install --pre "torch~=1.13"`

The only thing I've discovered that won't clobber is `pip install "torch==1.13.*" — but I don't think `pip-compile[-multi]` is capable of producing this in the lockfile.

**Comment by peterdemin** [comment]
Let me clarify. You have `torch==1.13.0a0+340c412` uploaded to an internal package index, which you want to install instead of the public version of torch 1.13.
I feel maybe the choice of version might have affected this. Can you try `torch==1.13.0.post999`? I think post-releases have higher priority than alpha.

**Comment by peterdemin** [comment]
If you have DevPI, or similar private package index, you can upload your own build.
According to https://peps.python.org/pep-0440/#pre-releases, alpha releases are considered lower than final releases. This means that 1.13.0 > 1.13.0a0+340c412, and so pip-tools will prefer them to custom builds.
